const EndPoints = {
  HOST_URL: 'http://172.105.36.16:8080',
  LOGIN: '/hourglass/authenticate/login.api',
  GET_USER_BY_ID: '/hourglass/user/getUserByUserId',
  HIRING_MANGER: '/job-post/user/list-all-hmanager.api',
  JOB_TYPE: '/common/rest/job-type.api',
  TIMESHEET_FREQ: '/common/rest/getTimeFrequencyList.api',
  PAY_TERMS: '/common/rest/list-pay-terms.api',
  LEGAL_ENTITY: '/common/rest/getCompanyList.api',
  PLANT_LIST: '/hourglass/plant/plant/listPlantsForCompnay', // Lokesh 11-Jul-23 -> Changed API as per Backend team request.
  BUSINESS_UNIT: '/job-post/business-unit/list.api',
  COST_CENTER: '/job-post/cost-center/list.api',
  CREATE_JOB: '/job-post/create.api',
  DRAFT_JOB: '/job-post/saveDraftJobPost.api',
  LIST_JOBS: '/job-post/list.api',
  GET_JOB_POST_COUNT: '/job-post/getJobPostCounts.api',
  GET_JOB_DETAILS: '/vendor/jobDetails.api',
  DOCUMENTS_LIST_JOB: '/hourglass/document/listJobPostDocuments',
  DOWNLOAD_DOC: '/hourglass/document/getAttachment',
  JOB_SEEKERS_LIST: '/hourglass/job-application/listJobApplicationSeeker',
  INTERVIEWED_LIST: '/hourglass/job-application/listScreenedJobApplications',
  APPLICATION_DETAILS: '/hourglass/job-application/getJobApplicationDetails',
  APPLICATION_DOCUMENTS: '/hourglass/job-application/getJobApplicationDetails',
  UPDATE_APPL_STATUS: '/hourglass/job-application/updateStatus',
  GET_USER: '/hourglass/user/getUserByUserId',
  APPLY_JOB_VENDOR: '/vendor/createJobApplication.api',
  JOB_COUNTS: '/job-post/getJobPostCounts.api',
  ALL_WORK_ORDERS: '/hourglass/work-order/listWorkOrders.api',
  WORK_ORDER_STATUS: '/hourglass/work-order/listWorkOrderStatus',
  CREATE_WORK_ORDER: '/hourglass/work-order/create.api',
  GET_VENDORS_LIST: '/vendor/getVendorDetails.api',
  SEND_JOB_OFFER: '/hourglass/job-offer/create.api',
  GET_DOCUMENTS: '/hourglass/document/list',
  GET_APPL_DETAILS:
    '/hourglass/job-application/getJobApplicationDetailsForJobPostId',
  GET_FULL_APPL_DETAILS: '/hourglass/user/getWorkForceDetails',
  GET_OFFER_LETTER_APPL:
    '/hourglass/job-offer/getJobOfferDetailsForJobApplication',
  ACCEPT_OFFER_LETTER: '/hourglass/job-offer/acceptJobOffer',
  REJECT_OFFER_LETTER: '/hourglass/job-offer/rejectJobOffer',
  GET_VENDOR_STAFF_DETAILS: '/hourglass/user/listUserForVendor',
  CREATE_WORK_FORCE: '/hourglass/work-force/create.api',
};

export default EndPoints;
