const EndPoints = {
  HOST_URL: 'http://172.105.36.16:8080',
  LOGIN: '/hourglass/authenticate/login.api',
  LOGOUT: '/hourglass/authenticate/logout',
  GET_USER_BY_ID: '/hourglass/user/getUserByUserId',
  HIRING_MANGER: '/hourglass/job-post/user/list-all-hmanager.api',
  JOB_TYPE: '/hourglass/common/rest/job-type.api',
  TIMESHEET_FREQ: '/hourglass/common/rest/getTimeFrequencyList.api',
  PAY_TERMS: '/hourglass/common/rest/list-pay-terms.api',
  LEGAL_ENTITY: '/hourglass/common/rest/getCompanyList.api',
  PLANT_LIST: '/hourglass/plant/plant/listPlantsForCompnay', // Lokesh 11-Jul-23 -> Changed API as per Backend team request.
  BUSINESS_UNIT: '/hourglass/job-post/business-unit/list.api',
  COST_CENTER: '/hourglass/job-post/cost-center/list.api',
  CREATE_JOB: '/hourglass/job-post/create.api',
  DRAFT_JOB: '/hourglass/job-post/saveDraftJobPost.api',
  LIST_JOBS: '/hourglass/job-post/list.api',
  GET_JOB_POST_COUNT: '/hourglass/job-post/getJobPostCounts.api',
  GET_JOB_DETAILS: '/hourglass/vendor/jobDetails.api',
  DOCUMENTS_LIST_JOB: '/hourglass/document/listJobPostDocuments',
  DOWNLOAD_DOC: '/hourglass/document/getAttachment',
  JOB_SEEKERS_LIST: '/hourglass/job-application/listJobApplicationSeeker',
  INTERVIEWED_LIST: '/hourglass/job-application/listScreenedJobApplications',
  APPLICATION_DETAILS: '/hourglass/job-application/getJobApplicationDetails',
  APPLICATION_DOCUMENTS: '/hourglass/job-application/getJobApplicationDetails',
  UPDATE_APPL_STATUS: '/hourglass/job-application/updateStatus',
  GET_USER: '/hourglass/user/getUserByUserId',
  APPLY_JOB_VENDOR: '/hourglass/vendor/createJobApplication.api',
  JOB_COUNTS: '/hourglass/job-post/getJobPostCounts.api',
  ALL_WORK_ORDERS: '/hourglass/work-order/listWorkOrders.api',
  WORK_ORDER_STATUS: '/hourglass/work-order/listWorkOrderStatus',
  CREATE_WORK_ORDER: '/hourglass/work-order/create.api',
  GET_VENDORS_LIST: '/hourglass/common/rest/listAllVendors',
  SEND_JOB_OFFER: '/hourglass/job-offer/create.api',
  GET_DOCUMENTS: '/hourglass/document/list',
  GET_APPL_DETAILS:
    '/hourglass/job-application/getJobApplicationDetailsForJobPostId',
  GET_FULL_APPL_DETAILS: '/hourglass/work-force/getWorkForceDetails.api',
  GET_OFFER_LETTER_APPL:
    '/hourglass/job-offer/getJobOfferDetailsForJobApplication',
  ACCEPT_OFFER_LETTER: '/hourglass/job-offer/acceptJobOffer',
  REJECT_OFFER_LETTER: '/hourglass/job-offer/rejectJobOffer',
  GET_VENDOR_STAFF_DETAILS: '/hourglass/user/listUserForVendor',
  GET_USER_FOR_JOBS: '/hourglass/work-force/listWorkForceForVendor',
  CREATE_WORK_FORCE: '/hourglass/work-force/create.api',
  LIST_WORK_FORCE: '/hourglass/work-force/listAllWorkForce.api',
  GET_WORK_FORCE: '/hourglass/work-force/getWorkForceDetails.api',
  TASK_LIST_HM: '/hourglass/task/listTasks.api',
  CREATE_TASK: '/hourglass/task/create.api',
  UPDATE_TASK: '/hourglass/task/updateTask.api',
  DELETE_TASK: '/hourglass/task/delete.api',
  GET_VENDOR_DETAILS: '/hourglass/vendor/getVendorDetails.api',
  GET_JOBAPPL_COUNTS: '/hourglass/vendor/getJobApplicationCounts.api',
  GET_TASK_FOR_WORK_ORDER_LIST: '/hourglass/task/tasksForWorkOrderId.api',
  GET_TIME_SHEET: '/hourglass/timesheet/listTimeSheet.api',
  GET_TIME_SHEET_NOTIFICATION:
    '/hourglass/timesheet/notification/listInbox.api',
  GET_TIME_SHEET_DETAILS: '/hourglass/timesheet/getTimeSheetDetails.api',
  CREATE_TIME_SHEET: '/hourglass/timesheet/create.api',
  CREATE_TIME_SHEET_AS_DRAFT: '/hourglass/timesheet/saveDraftTimeSheet.api',
  GET_APPL_LOGS: '/hourglass/audit-log/auditLogForJobApplication.api',
  GET_WORKORDER_LOGS: '/hourglass/audit-log/auditLogForWorkOrder.api',
  GET_ATTACHMENT: '/hourglass/document/getAttachment',
  UPLOAD_WORK_FORCE_PIC:
    '/hourglass/work-force/uploadProfilePicForWorkForce.api',
  GET_WORK_FORCE_PIC: '/hourglass/document/getProfilePicForWorkForce.api',
  GET_JOB_APPL_PIC: '/hourglass/document/getProfilePicForJobApplication.api',
  UPLOAD_WORK_FORCE_DOCUMENT:
    '/hourglass/work-force/uploadFilesForWorkForce.api',
  UPLOAD_TIME_SHEET_DOCUMENT:
    '/hourglass/timesheet/uploadFilesForTimeSheet.api',
  REMOVE_TASK_FROM_TIMESHEET: '/hourglass/timesheet/removeTaskForTimeSheet.api',
  WORKORDER_NOTIFICATION: '/hourglass/work-order/notification/listInbox.api',
  GET_TIMESHEET_STATUS: '/hourglass/common/listTimeSheetStatus.api',
  GET_TIMESHEET_LOGS: '/hourglass/audit-log/auditLogForTimeSheet.api',
  UPDATE_TIMESHEET_STATUS: '/hourglass/timesheet/updateTimeSheetStatus.api',
  GET_INVOICE: '/hourglass/payment/invoice/listInvoice.api',
  TIMESHEET_LIST_HM: '/hourglass/timesheet/listTimeSheetForInvoice.api',
  CREATE_INVOICE: '/hourglass/payment/invoice/create.api',
  GET_TIME_SHEET_OUTBOX: '/hourglass/timesheet/notification/listOutbox.api',
};

export default EndPoints;
